### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [b-t-k/carey-rockwell_stand-by-for-mars#1]
- `typogrify` makes changes, please run it again
- Chapters must be headed with Roman numerals only. See https://standardebooks.org/contribute/typography#chapters
- ToC will need to be modified with correct Roman semantics. Please do not put inline contents on their own lines, they should be on the same line as the opening tag. (For example in the ToC look at the code style for Chapter 22 vs the colophon right after it.)
- There is one `<i>` tag that should be an `<em>`
- Metadata:
    - "A Tom Corbett Space Cadet Adventure" is not a subtitle, it is just a qualifier. (Presumably there are more than one such novels.) We can remove it.
    - Instead of using durendal.org as a source, use the DP OLS source instead: https://www.pgdp.org/ols/tools/biblio.php?id=projectID43efed53d919f  durendal.org is a personal website and could go offline eventually, but DP OLS is an organization so we can expect it to be up indefinitely. You'll have to update the imprint and colophon as well.
    - Typo: "started as tv show" -> "started as a TV show"
    - Capitalize all instances of TV
    - Write out "5" as "five"
    - No spaces between em dashes (last p)
    - Last p: link to the site using `<a href>Tom Corbett Space Cadet website</a>`, no need to include the URL as non-linked text
    - Last p: "it's" -> "its"
    - Please put a period after B in your name in the metadata
- Colophon:
    - Missing publication year
    - `<abbr class="name">` around your initial

**Comment by b-t-k** [comment]
Typogrify is 90% about ellipses at the end of a sentences. I will double check but if I recall they are all sentences that trail off meaning it should be ellipses space period. Typogrify wants to change them to period space ellipses.

Do you want me to change it anyway even thought it's technically incorrect?

"Last p: link to the site using <a href>Tom Corbett Space Cadet website</a>, no need to include the URL as non-linked text"
This is a bit unclear. Should I a) add the link or b) delete the url?

And I am going to forget the period after the B every damn time as personally I never use it :-)

**Comment by acabal** [comment]
Do what typogrify does, in print the ellipses and period will look identical in terms of spacing. In the past there was often no differentiation between period + ellipses vs ellipses + period and they were used interchangeably, so we normalize them to our house style.

Add the link, and since it is linked it is not necessary to type out the URL after it.
